### ISSUE TITLE
random libtiff sigsegv on amazon linux in 8.7, but not 8.6

### ISSUE THREAD

**Issue by chregu** [libvips/libvips#1158]
Not sure it's a  vips issue, but it only happens in 8.7 (and master), but not 8.6.  
We see random, but reproducable segfaults on amazon linux with certain input tiff images (but not eg. on Ubuntu, which seems to have the same libtiff version, 4.0.3 )

A simple `vips VipsCopy input.tif output.jpg` can generate it. It happens maybe 1 out 3-5 times. 

Here's the backtrace I get on the segfault:
```
#0  TIFFScanlineSize64 (tif=0x0) at tif_strip.c:279
#1  0x00007ffff71bc655 in TIFFScanlineSize (tif=<optimized out>) at tif_strip.c:329
#2  0x00007ffff794900e in rtiff_stripwise_generate (or=0x7fffdc00ce40, seq=<optimized out>, a=0x7fffe800a840, b=<optimized out>, stop=<optimized out>) at tiff2vips.c:1822
#3  0x00007ffff797a351 in vips_region_generate (reg=0x7fffdc00ce40) at region.c:1590
#4  0x00007ffff797b475 in vips_region_prepare_to_generate (reg=0x7fffdc00ce40, dest=0x7fffd0001ee0, r=0x7fffedffa5f0, x=0, y=2016) at region.c:1716
#5  0x00007ffff797da3f in vips_region_prepare_to (reg=reg@entry=0x7fffdc00ce40, dest=0x7fffd0001ee0, r=r@entry=0x7fffe806027c, x=0, y=2016) at region.c:1856
#6  0x00007ffff78dabda in vips_tile_cache_gen (or=0x7fffd0001cd0, seq=0x7fffdc00ce40, a=<optimized out>, b=0x7fffe80022f0, stop=0x7fffedffa6cc) at tilecache.c:679
#7  0x00007ffff797a351 in vips_region_generate (reg=0x7fffd0001cd0) at region.c:1590
#8  0x00007ffff797af79 in vips_region_fill (reg=reg@entry=0x7fffd0001cd0, r=r@entry=0x7fffd0001c78, fn=fn@entry=0x7ffff797a310 <vips_region_generate>, a=a@entry=0x0) at region.c:905
#9  0x00007ffff797d853 in vips_region_prepare (reg=reg@entry=0x7fffd0001cd0, r=r@entry=0x7fffd0001c78) at region.c:1659
#10 0x00007ffff78dbb6d in vips_sequential_generate (or=0x7fffd0001c20, seq=0x7fffd0001cd0, a=<optimized out>, b=0x6b5e40, stop=<optimized out>) at sequential.c:167
#11 0x00007ffff797a351 in vips_region_generate (reg=0x7fffd0001c20) at region.c:1590
#12 0x00007ffff797af79 in vips_region_fill (reg=reg@entry=0x7fffd0001c20, r=r@entry=0x7fffd0001bc8, fn=fn@entry=0x7ffff797a310 <vips_region_generate>, a=a@entry=0x0) at region.c:905
#13 0x00007ffff797d853 in vips_region_prepare (reg=reg@entry=0x7fffd0001c20, r=r@entry=0x7fffd0001bc8) at region.c:1659
#14 0x00007ffff796db09 in vips_image_write_gen (or=0x7fffd0001b70, seq=0x7fffd0001c20, a=<optimized out>, b=<optimized out>, stop=<optimized out>) at image.c:2497
#15 0x00007ffff797a351 in vips_region_generate (reg=0x7fffd0001b70) at region.c:1590
#16 0x00007ffff797af79 in vips_region_fill (reg=reg@entry=0x7fffd0001b70, r=r@entry=0x7fffd0001b18, fn=fn@entry=0x7ffff797a310 <vips_region_generate>, a=a@entry=0x0) at region.c:905
#17 0x00007ffff797d853 in vips_region_prepare (reg=reg@entry=0x7fffd0001b70, r=r@entry=0x7fffd0001b18) at region.c:1659
#18 0x00007ffff793f8e9 in vips_foreign_load_generate (or=0x7fffd0001ac0, seq=0x7fffd0001b70, a=<optimized out>, b=<optimized out>, stop=<optimized out>) at foreign.c:881
#19 0x00007ffff797a351 in vips_region_generate (reg=0x7fffd0001ac0) at region.c:1590
#20 0x00007ffff797af79 in vips_region_fill (reg=reg@entry=0x7fffd0001ac0, r=r@entry=0x7fffd0001a68, fn=fn@entry=0x7ffff797a310 <vips_region_generate>, a=a@entry=0x0) at region.c:905
#21 0x00007ffff797d853 in vips_region_prepare (reg=reg@entry=0x7fffd0001ac0, r=r@entry=0x7fffd0001a68) at region.c:1659
#22 0x00007ffff78e0a69 in vips_copy_gen (or=0x7fffd0001a10, seq=0x7fffd0001ac0, a=<optimized out>, b=<optimized out>, stop=<optimized out>) at copy.c:139
#23 0x00007ffff797a351 in vips_region_generate (reg=0x7fffd0001a10) at region.c:1590
#24 0x00007ffff797af79 in vips_region_fill (reg=reg@entry=0x7fffd0001a10, r=r@entry=0x7fffd00019b8, fn=fn@entry=0x7ffff797a310 <vips_region_generate>, a=a@entry=0x0) at region.c:905
#25 0x00007ffff797d853 in vips_region_prepare (reg=reg@entry=0x7fffd0001a10, r=r@entry=0x7fffd00019b8) at region.c:1659
#26 0x00007ffff796db09 in vips_image_write_gen (or=0x7fffd0001960, seq=0x7fffd0001a10, a=<optimized out>, b=<optimized out>, stop=<optimized out>) at image.c:2497
#27 0x00007ffff797a351 in vips_region_generate (reg=0x7fffd0001960) at region.c:1590
#28 0x00007ffff797af79 in vips_region_fill (reg=reg@entry=0x7fffd0001960, r=r@entry=0x7fffd0001908, fn=fn@entry=0x7ffff797a310 <vips_region_generate>, a=a@entry=0x0) at region.c:905
#29 0x00007ffff797d853 in vips_region_prepare (reg=reg@entry=0x7fffd0001960, r=r@entry=0x7fffd0001908) at region.c:1659
#30 0x00007ffff78e0a69 in vips_copy_gen (or=0x7fffd00018b0, seq=0x7fffd0001960, a=<optimized out>, b=<optimized out>, stop=<optimized out>) at copy.c:139
#31 0x00007ffff797a351 in vips_region_generate (reg=0x7fffd00018b0) at region.c:1590
#32 0x00007ffff797af79 in vips_region_fill (reg=reg@entry=0x7fffd00018b0, r=r@entry=0x7fffd0001858, fn=fn@entry=0x7ffff797a310 <vips_region_generate>, a=a@entry=0x0) at region.c:905
#33 0x00007ffff797d853 in vips_region_prepare (reg=reg@entry=0x7fffd00018b0, r=r@entry=0x7fffd0001858) at region.c:1659
#34 0x00007ffff78dc951 in vips_flatten_black_gen (or=0x7fffd0001800, vseq=0x7fffd00018b0, a=<optimized out>, b=0x6b5810, stop=<optimized out>) at flatten.c:173
#35 0x00007ffff797a351 in vips_region_generate (reg=0x7fffd0001800) at region.c:1590
#36 0x00007ffff797af79 in vips_region_fill (reg=reg@entry=0x7fffd0001800, r=r@entry=0x7fffd8002768, fn=fn@entry=0x7ffff797a310 <vips_region_generate>, a=a@entry=0x0) at region.c:905
#37 0x00007ffff797d853 in vips_region_prepare (reg=reg@entry=0x7fffd0001800, r=r@entry=0x7fffd8002768) at region.c:1659
#38 0x00007ffff796db09 in vips_image_write_gen (or=0x7fffd8002710, seq=0x7fffd0001800, a=<optimized out>, b=<optimized out>, stop=<optimized out>) at image.c:2497
#39 0x00007ffff797a351 in vips_region_generate (reg=0x7fffd8002710) at region.c:1590
#40 0x00007ffff797b475 in vips_region_prepare_to_generate (reg=0x7fffd8002710, dest=0x6ac2f0, r=0x7fffedffae40, x=0, y=2239) at region.c:1716
#41 0x00007ffff797da3f in vips_region_prepare_to (reg=0x7fffd8002710, dest=0x6ac2f0, r=r@entry=0x7fffdc0019d0, x=0, y=2239) at region.c:1856
#42 0x00007ffff7974b88 in wbuffer_work_fn (state=0x7fffdc001970, a=<optimized out>) at sinkdisc.c:425
#43 0x00007ffff797e1cc in vips_thread_work_unit (thr=0x6d1c30) at threadpool.c:658
#44 vips_thread_main_loop (a=0x6d1c30) at threadpool.c:681
#45 0x00007ffff797dfc4 in vips_thread_run (data=0x6d2030) at threadpool.c:207
#46 0x00007ffff681b075 in g_thread_proxy (data=0x6ab0f0) at gthread.c:798
#47 0x00007ffff5e2ade5 in start_thread (arg=0x7fffedffb700) at pthread_create.c:308
#48 0x00007ffff5b54bad in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113
```

And here's a Dockerfile for the whole setup https://gist.github.com/chregu/0d63c48f0f0986ee876cc6f5bbefe551 on which it is reproducable.

A Tiff image on which it is happening: https://www.dropbox.com/s/jfu19ubyxk048fp/input.tif?dl=0 

It looks like it doesn't happen with an uncompressed image. I could also reproduce it with other images exported from Photoshop, but this one segfaults faster than others.

Again, not sure if really a libvips issue, but something changed, since it's not happening in 8.6

**Comment by jcupitt** [comment]
Oh dear, that sounds bad. Thank you for the report @chregu, I'll investigate.

**Comment by jcupitt** [comment]
I'm seeing in on my laptop with Ubuntu 18.10 as well:

```bash
#!/bin/bash

set -e

for i in {1..1000}; do
        echo $i ...
        vips copy $1 x.jpg >& /dev/null
done
```

Perhaps one time in 20.

**Comment by chregu** [comment]
yep, that helped. Thanks for the quick suggestion. And let's hope you'll find a better solution soon (can't judge, if the current one is bad or not ;))

**Comment by felixbuenemann** [comment]
@jcupitt Is this issue fixed by b84bf6d or is that code only for debugging?

**Comment by jcupitt** [comment]
Hiya, it should be fixed now in git master. It took ages to track down: plane separate TIFFs with a large rows-per-strip could cause a cache to under-size. Yuk!

Thanks for the report, @chregu!

**Comment by jcupitt** [comment]
Yes @felixbuenemann, that was just a bit of useful extra tracking code.
