### ISSUE TITLE
Segmentation fault for specific pdf in alpine linux docker container

### ISSUE THREAD

**Issue by priyankatapar** [libvips/libvips#1288]
Hello,

We are facing Seg fault issue for a specific PDF file in **vips v8.7.4** only on alpine linux. Here is the core dump:

```
#525 0x00007ffff6ca5142 in TextBlock::visitDepthFirst(TextBlock*, int, TextBlock**, int, bool*, TextBlock**, int) () at /usr/lib/libpoppler.so.67
#526 0x00007ffff6ca5142 in TextBlock::visitDepthFirst(TextBlock*, int, TextBlock**, int, bool*, TextBlock**, int) () at /usr/lib/libpoppler.so.67
#527 0x00007ffff6ca5142 in TextBlock::visitDepthFirst(TextBlock*, int, TextBlock**, int, bool*, TextBlock**, int) () at /usr/lib/libpoppler.so.67
#528 0x00007ffff6ca5142 in TextBlock::visitDepthFirst(TextBlock*, int, TextBlock**, int, bool*, TextBlock**, int) () at /usr/lib/libpoppler.so.67
#529 0x00007ffff6ca5142 in TextBlock::visitDepthFirst(TextBlock*, int, TextBlock**, int, bool*, TextBlock**, int) () at /usr/lib/libpoppler.so.67
#530 0x00007ffff6ca5142 in TextBlock::visitDepthFirst(TextBlock*, int, TextBlock**, int, bool*, TextBlock**, int) () at /usr/lib/libpoppler.so.67
#531 0x00007ffff6ca5142 in TextBlock::visitDepthFirst(TextBlock*, int, TextBlock**, int, bool*, TextBlock**, int) () at /usr/lib/libpoppler.so.67
#532 0x00007ffff6ca5142 in TextBlock::visitDepthFirst(TextBlock*, int, TextBlock**, int, bool*, TextBlock**, int) () at /usr/lib/libpoppler.so.67
#533 0x00007ffff6ca5142 in TextBlock::visitDepthFirst(TextBlock*, int, TextBlock**, int, bool*, TextBlock**, int) () at /usr/lib/libpoppler.so.67
#534 0x00007ffff6ca5142 in TextBlock::visitDepthFirst(TextBlock*, int, TextBlock**, int, bool*, TextBlock**, int) () at /usr/lib/libpoppler.so.67
#535 0x00007ffff6ca5142 in TextBlock::visitDepthFirst(TextBlock*, int, TextBlock**, int, bool*, TextBlock**, int) () at /usr/lib/libpoppler.so.67
#536 0x00007ffff6ca5142 in TextBlock::visitDepthFirst(TextBlock*, int, TextBlock**, int, bool*, TextBlock**, int) () at /usr/lib/libpoppler.so.67
#537 0x00007ffff6ca5142 in TextBlock::visitDepthFirst(TextBlock*, int, TextBlock**, int, bool*, TextBlock**, int) () at /usr/lib/libpoppler.so.67
#538 0x00007ffff6ca5142 in TextBlock::visitDepthFirst(TextBlock*, int, TextBlock**, int, bool*, TextBlock**, int) () at /usr/lib/libpoppler.so.67
#539 0x00007ffff6ca5142 in TextBlock::visitDepthFirst(TextBlock*, int, TextBlock**, int, bool*, TextBlock**, int) () at /usr/lib/libpoppler.so.67
#540 0x00007ffff6ca5142 in TextBlock::visitDepthFirst(TextBlock*, int, TextBlock**, int, bool*, TextBlock**, int) () at /usr/lib/libpoppler.so.67
#541 0x00007ffff6ca5142 in TextBlock::visitDepthFirst(TextBlock*, int, TextBlock**, int, bool*, TextBlock**, int) () at /usr/lib/libpoppler.so.67
#542 0x00007ffff6ca5142 in TextBlock::visitDepthFirst(TextBlock*, int, TextBlock**, int, bool*, TextBlock**, int) () at /usr/lib/libpoppler.so.67
#543 0x00007ffff6ca5142 in TextBlock::visitDepthFirst(TextBlock*, int, TextBlock**, int, bool*, TextBlock**, int) () at /usr/lib/libpoppler.so.67
#544 0x00007ffff6ca5142 in TextBlock::visitDepthFirst(TextBlock*, int, TextBlock**, int, bool*, TextBlock**, int) () at /usr/lib/libpoppler.so.67
#545 0x00007ffff6ca5142 in TextBlock::visitDepthFirst(TextBlock*, int, TextBlock**, int, bool*, TextBlock**, int) () at /usr/lib/libpoppler.so.67
#546 0x00007ffff6ca5142 in TextBlock::visitDepthFirst(TextBlock*, int, TextBlock**, int, bool*, TextBlock**, int) () at /usr/lib/libpoppler.so.67
#547 0x00007ffff6ca5142 in TextBlock::visitDepthFirst(TextBlock*, int, TextBlock**, int, bool*, TextBlock**, int) () at /usr/lib/libpoppler.so.67
#548 0x00007ffff6ca5142 in TextBlock::visitDepthFirst(TextBlock*, int, TextBlock**, int, bool*, TextBlock**, int) () at /usr/lib/libpoppler.so.67
#549 0x00007ffff6ca5142 in TextBlock::visitDepthFirst(TextBlock*, int, TextBlock**, int, bool*, TextBlock**, int) () at /usr/lib/libpoppler.so.67
#550 0x00007ffff6ca5142 in TextBlock::visitDepthFirst(TextBlock*, int, TextBlock**, int, bool*, TextBlock**, int) () at /usr/lib/libpoppler.so.67
#551 0x00007ffff6ca5142 in TextBlock::visitDepthFirst(TextBlock*, int, TextBlock**, int, bool*, TextBlock**, int) () at /usr/lib/libpoppler.so.67
#552 0x00007ffff6ca5142 in TextBlock::visitDepthFirst(TextBlock*, int, TextBlock**, int, bool*, TextBlock**, int) () at /usr/lib/libpoppler.so.67
#553 0x00007ffff6ca52b7 in TextBlock::visitDepthFirst(TextBlock*, int, TextBlock**, int, bool*) () at /usr/lib/libpoppler.so.67
#554 0x00007ffff6ca6eb1 in TextPage::coalesce(bool, double, bool) () at /usr/lib/libpoppler.so.67
#555 0x00007ffff6c424a1 in Gfx::~Gfx() () at /usr/lib/libpoppler.so.67
#556 0x00007ffff6c74d1d in Page::displaySlice(OutputDev*, double, double, int, bool, bool, int, int, int, int, bool, bool (*)(void*), void*, bool (*)(Annot*, void*), void*, bool) () at /usr/lib/libpoppler.so.67
#557 0x00007ffff742667d in  () at /usr/lib/libpoppler-glib.so.8
#558 0x00007ffff7c6947e in vips_foreign_load_pdf_generate (or=0x5555556c0030, seq=0x0, a=0x55555565f0c0, b=0x0, stop=0x7ffff652aa8c) at pdfload.c:390
#559 0x00007ffff7ce2862 in vips_region_generate (reg=0x5555556c0030) at region.c:1590
#560 0x00007ffff7ce2ae4 in vips_region_prepare_to_generate (reg=0x5555556c0030, dest=0x5555556c00e0, r=0x7ffff652ab60, x=0, y=0) at region.c:1716
#561 0x00007ffff7ce2dfe in vips_region_prepare_to (reg=0x5555556c0030, dest=0x5555556c00e0, r=0x55555570ebbc, x=0, y=0) at region.c:1834
#562 0x00007ffff7bcdde2 in vips_tile_cache_gen (or=0x5555556bbee0, seq=0x5555556c0030, a=0x5555556b54c0, b=0x5555556bbd80, stop=0x7ffff652ac9c) at tilecache.c:679
#563 0x00007ffff7bce557 in vips_line_cache_gen (or=0x5555556bbee0, seq=0x5555556c0030, a=0x5555556b54c0, b=0x5555556bbd80, stop=0x7ffff652ac9c) at tilecache.c:910
#564 0x00007ffff7ce2862 in vips_region_generate (reg=0x5555556bbee0) at region.c:1590
#565 0x00007ffff7cdd29d in vips_region_fill (reg=0x5555556bbee0, r=0x5555556bbe88, fn=0x7ffff7ce27e4 <vips_region_generate>, a=0x0) at region.c:905
#566 0x00007ffff7ce2997 in vips_region_prepare (reg=0x5555556bbee0, r=0x5555556bbe88) at region.c:1659
#567 0x00007ffff7ccbbaf in vips_image_write_gen (or=0x5555556bbe30, seq=0x5555556bbee0, a=0x5555556b5650, b=0x0, stop=0x7ffff652adcc) at image.c:2497
#568 0x00007ffff7ce2862 in vips_region_generate (reg=0x5555556bbe30) at region.c:1590
#569 0x00007ffff7cdd29d in vips_region_fill (reg=0x5555556bbe30, r=0x5555556bbd28, fn=0x7ffff7ce27e4 <vips_region_generate>, a=0x0) at region.c:905
#570 0x00007ffff7ce2997 in vips_region_prepare (reg=0x5555556bbe30, r=0x5555556bbd28) at region.c:1659
#571 0x00007ffff7c7de93 in vips_foreign_load_generate (or=0x5555556bbcd0, seq=0x5555556bbe30, a=0x0, b=0x55555565f0c0, stop=0x7ffff652aefc) at foreign.c:881
#572 0x00007ffff7ce2862 in vips_region_generate (reg=0x5555556bbcd0) at region.c:1590
#573 0x00007ffff7cdd29d in vips_region_fill (reg=0x5555556bbcd0, r=0x5555556bbbc8, fn=0x7ffff7ce27e4 <vips_region_generate>, a=0x0) at region.c:905
#574 0x00007ffff7ce2997 in vips_region_prepare (reg=0x5555556bbcd0, r=0x5555556bbbc8) at region.c:1659
#575 0x00007ffff7ccbbaf in vips_image_write_gen (or=0x5555556bbb70, seq=0x5555556bbcd0, a=0x555555661000, b=0x0, stop=0x7ffff652b02c) at image.c:2497
#576 0x00007ffff7ce2862 in vips_region_generate (reg=0x5555556bbb70) at region.c:1590
#577 0x00007ffff7cdd29d in vips_region_fill (reg=0x5555556bbb70, r=0x5555556bbc78, fn=0x7ffff7ce27e4 <vips_region_generate>, a=0x0) at region.c:905
#578 0x00007ffff7ce2997 in vips_region_prepare (reg=0x5555556bbb70, r=0x5555556bbc78) at region.c:1659
#579 0x00007ffff7ccbbaf in vips_image_write_gen (or=0x5555556bbc20, seq=0x5555556bbb70, a=0x555555661e10, b=0x0, stop=0x7ffff652b15c) at image.c:2497
#580 0x00007ffff7ce2862 in vips_region_generate (reg=0x5555556bbc20) at region.c:1590
#581 0x00007ffff7ce2ae4 in vips_region_prepare_to_generate (reg=0x5555556bbc20, dest=0x5555556adac0, r=0x7ffff652b230, x=0, y=0) at region.c:1716
#582 0x00007ffff7ce2dfe in vips_region_prepare_to (reg=0x5555556bbc20, dest=0x5555556adac0, r=0x5555556ba100, x=0, y=0) at region.c:1834
#583 0x00007ffff7cd3dae in wbuffer_work_fn (state=0x5555556ba0a0, a=0x7fffffffe580) at sinkdisc.c:425
#584 0x00007ffff7ce4005 in vips_thread_work_unit (thr=0x5555556b4ba0) at threadpool.c:658
#585 0x00007ffff7ce4084 in vips_thread_main_loop (a=0x5555556b4ba0) at threadpool.c:681
#586 0x00007ffff7ce378a in vips_thread_run (data=0x5555556bf000) at threadpool.c:207
#587 0x00007ffff79fc915 in  () at /usr/lib/libglib-2.0.so.0
#588 0x00007ffff7fbe4d8 in  () at /lib/ld-musl-x86_64.so.1
#589 0x0000000000000000 in  ()
```

Anyone faced similar issue, did they find any solution to fix this?
Thanks!

**Comment by lovell** [comment]
Is this a duplicate of #1287 ?

**Comment by priyankatapar** [comment]
yes #1287 said timed out while creation, so created this new one. I will close this issue. Thanks @lovell
