### ISSUE TITLE
.gif/.png seems to be tried to be loaded as .jpg

### ISSUE THREAD

**Issue by linkyndy** [libvips/libvips#1343]
I've seen the following error while trying to load and process a `.gif` image with libvips:

```
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Premature end of JPEG file
VipsJpeg: Premature end of JPEG file
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Premature end of JPEG file
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Corrupt JPEG data: premature end of data segment
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Corrupt JPEG data: premature end of data segment
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Corrupt JPEG data: premature end of data segment
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Corrupt JPEG data: 170 extraneous bytes before marker 0xdb
VipsJpeg: Corrupt JPEG data: 170 extraneous bytes before marker 0xdb
VipsJpeg: Corrupt JPEG data: 170 extraneous bytes before marker 0xdb
VipsJpeg: Corrupt JPEG data: 170 extraneous bytes before marker 0xdb
VipsJpeg: Corrupt JPEG data: 170 extraneous bytes before marker 0xdb
VipsJpeg: Corrupt JPEG data: 170 extraneous bytes before marker 0xdb
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Corrupt JPEG data: premature end of data segment
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Premature end of JPEG file
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Premature end of JPEG file
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Corrupt JPEG data: premature end of data segment
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Premature end of JPEG file
gifload: bad frame size
````

Why does it try to load the file as a `.jpg`? And also, what does the `gifload: bad frame size` mean? I've tried running the same sequence of operations in Python with Pillow and Imagemagick, and it succeeded 🤔

**Comment by linkyndy** [comment]
I also just saw this for `.png` file:

```
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Corrupt JPEG data: 55 extraneous bytes before marker 0xd0
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Premature end of JPEG file
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Premature end of JPEG file
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Premature end of JPEG file
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Premature end of JPEG file
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Corrupt JPEG data: 1 extraneous bytes before marker 0xe0
VipsJpeg: Corrupt JPEG data: 1 extraneous bytes before marker 0xe0
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Corrupt JPEG data: bad Huffman code
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Premature end of JPEG file
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
```

**Comment by jcupitt** [comment]
Sorry, no idea, you'd need to share some sample code or a sample image.

Are you perhaps calling `jpegload` directly? That might produce errors like this. Or perhaps a badly corrupted file. Or maybe memory corruption if you are loading from a buffer.

**Comment by linkyndy** [comment]
I can't share any image, unfortunately. The code is the same as before:

```ruby
image = Vips::Image.new_from_file(filename, access: :sequential)
image = image.colourspace(:srgb)
image = image.flatten(background: [255, 255, 255]) if image.has_alpha?
image.write_to_memory
```

I'm not calling `jpegload` directly. I'm not sure how `jpegload` is invoked  from the `new_from_file` call; how does libvips determine the loader?

Memory corruption is not the case; however, corrupted images are a possibility.

**Comment by linkyndy** [comment]
I tried playing with some of my sample files locally and I noticed something interesting:

```
irb(main):014:0> Vips::Image.new_from_file('RAW_CANON_1DM2.CR2')

(bundle:86090): VIPS-WARNING **: 13:58:54.638: Photometric tag is missing, assuming data is YCbCr

(bundle:86090): VIPS-WARNING **: 13:58:54.638: SamplesPerPixel tag is missing, applying correct SamplesPerPixel value of 3

(bundle:86090): VIPS-WARNING **: 13:58:54.638: Subsampling tag is not set, yet subsampling inside JPEG data [2,1] does not match default values [2,2]; assuming subsampling inside JPEG data is correct

(bundle:86090): VIPS-WARNING **: 13:58:54.639: Photometric tag is missing, assuming data is YCbCr

(bundle:86090): VIPS-WARNING **: 13:58:54.639: SamplesPerPixel tag is missing, applying correct SamplesPerPixel value of 3

(bundle:86090): VIPS-WARNING **: 13:58:54.639: Subsampling tag is not set, yet subsampling inside JPEG data [2,1] does not match default values [2,2]; assuming subsampling inside JPEG data is correct

(bundle:86090): VIPS-WARNING **: 13:58:54.639: Photometric tag is missing, assuming data is YCbCr

(bundle:86090): VIPS-WARNING **: 13:58:54.639: SamplesPerPixel tag is missing, applying correct SamplesPerPixel value of 3

(bundle:86090): VIPS-WARNING **: 13:58:54.639: Subsampling tag is not set, yet subsampling inside JPEG data [2,1] does not match default values [2,2]; assuming subsampling inside JPEG data is correct
Traceback (most recent call last):
       [...snip...]
        4: from (irb):14
        3: from /.../.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/ruby-vips-2.0.13/lib/vips/image.rb:264:in `new_from_file'
        2: from /.../.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/ruby-vips-2.0.13/lib/vips/operation.rb:330:in `call'
        1: from /.../.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/ruby-vips-2.0.13/lib/vips/operation.rb:74:in `build'
Vips::Error (tiff2vips: subsampled images not supported)
irb(main):015:0> Vips::Image.magickload('RAW_CANON_1DM2.CR2')
=> #<Image 3522x2348 ushort, 3 bands, rgb16>
```

The image is [this one](https://github.com/libvips/libvips/files/3301372/RAW_CANON_1DM2.CR2.zip). I understood that libvips doesn't deal with RAW files, but dispatches to imagemagick. If that's the case, then why is libtiff called here instead? 🤔 

Another example is this file:
[RAW_NIKON1_V1.NEF.zip](https://github.com/libvips/libvips/files/3301383/RAW_NIKON1_V1.NEF.zip)

```
irb(main):005:0> Vips::Image.new_from_file('/Users/andrei/Downloads/RAW_NIKON1_V1.NEF')

(bundle:86090): VIPS-WARNING **: 13:53:03.035: Unknown field with tag 36867 (0x9003) encountered

(bundle:86090): VIPS-WARNING **: 13:53:03.037: Unknown field with tag 37398 (0x9216) encountered

(bundle:86090): VIPS-WARNING **: 13:53:03.037: ASCII value for tag "Software" contains null byte in value; value incorrectly truncated during reading due to implementation limitations

(bundle:86090): VIPS-WARNING **: 13:53:03.037: Unknown field with tag 36867 (0x9003) encountered

(bundle:86090): VIPS-WARNING **: 13:53:03.037: Unknown field with tag 37398 (0x9216) encountered

(bundle:86090): VIPS-WARNING **: 13:53:03.037: ASCII value for tag "Software" contains null byte in value; value incorrectly truncated during reading due to implementation limitations

(bundle:86090): VIPS-WARNING **: 13:53:03.037: Unknown field with tag 36867 (0x9003) encountered

(bundle:86090): VIPS-WARNING **: 13:53:03.037: Unknown field with tag 37398 (0x9216) encountered

(bundle:86090): VIPS-WARNING **: 13:53:03.037: ASCII value for tag "Software" contains null byte in value; value incorrectly truncated during reading due to implementation limitations

(bundle:86090): VIPS-WARNING **: 13:53:03.038: Unknown field with tag 36867 (0x9003) encountered

(bundle:86090): VIPS-WARNING **: 13:53:03.038: Unknown field with tag 37398 (0x9216) encountered

(bundle:86090): VIPS-WARNING **: 13:53:03.038: ASCII value for tag "Software" contains null byte in value; value incorrectly truncated during reading due to implementation limitations

(bundle:86090): VIPS-WARNING **: 13:53:03.038: Unknown field with tag 36867 (0x9003) encountered

(bundle:86090): VIPS-WARNING **: 13:53:03.038: Unknown field with tag 37398 (0x9216) encountered

(bundle:86090): VIPS-WARNING **: 13:53:03.038: ASCII value for tag "Software" contains null byte in value; value incorrectly truncated during reading due to implementation limitations
=> #<Image 160x120 uchar, 3 bands, srgb>
irb(main):004:0> Vips::Image.magickload('/Users/andrei/Downloads/RAW_NIKON1_V1.NEF')
=> #<Image 3904x2604 ushort, 3 bands, rgb16>
```

The file is loaded in the end, but the resulting image is totally different than what imagemagick returns.

I am wondering, is this something related to libvips (a bug, or maybe a feature) or to some misconfigured library? Locally I am using:

```
$ brew info vips
vips: stable 8.8.0 (bottled)

$ brew info imagemagick
imagemagick: stable 7.0.8-48 (bottled), HEAD
```

**Comment by jcupitt** [comment]
NEF and CR2 files are TIFFs, but with extra and strange fields that libtiff does not recognise containing the raw camera data. If you try to load one with libvips, it will spot the TIFF magic number in the first few bytes and try to load with libtiff, producing the errors above.

You should be able to load them by calling `magickload` directly, eg.:

```ruby
image = Vips::Image.magickload(filename)
```

8.8.1 has an improvement here: rather than just sniffing the first few bytes to get the file type, it attempts to load the first directory of the TIFF with libtiff. If this fails, i trhen falls back to imagemagick. This should mean it works as expected in more cases.

**Comment by jcupitt** [comment]
Oh, libvips generally determines file type by sniffing the first few bytes, though some loaders will do more careful checks.

**Comment by linkyndy** [comment]
> NEF and CR2 files are TIFFs, but with extra and strange fields that libtiff does not recognise containing the raw camera data. If you try to load one with libvips, it will spot the TIFF magic number in the first few bytes and try to load with libtiff, producing the errors above.
> 
> You should be able to load them by calling `magickload` directly, eg.:
> 
> ```ruby
> image = Vips::Image.magickload(filename)
> ```

Are there specific error messages I can rescue from and attempt a `magickload` instead? I wouldn't want to "abuse" imagemagick more than necessary. Not only for RAW files, but for BMPs as well (and maybe other file types that currently fail sometimes -- like the ones in the first post).

**Comment by jcupitt** [comment]
I would check the filename suffix or the mime type if you have access to that. You could probably use the `file` command as well.

**Comment by linkyndy** [comment]
I tried calling `magickload` directly, but this caused big changes in CPU (doubled) and disk (a lot of spikes). This was caused by very long mean processing times:

![Screen Shot 2019-06-19 at 13 19 47](https://user-images.githubusercontent.com/319844/59761542-668fe700-9295-11e9-8924-d79c9c819103.png)

I've seen outliers that took 10mins to execute with `magickload`, versus 1ms for `new_from_file`. These mostly happened with CR2 images, independently of their size.

**Comment by jcupitt** [comment]
Yes, imagemagick handles CR2 / RAW / NEF etc. images by shelling out to `ufraw-batch`. You will see huge disc and mem spikes.

8.8.1 has an improvement here which should improve speed for these files.

Personally, I would either ban the upload of raw camera files, or perhaps not show a preview for them, just a generic icon (this is what google drive does, for example). The point of these files is to give the photographer control over the conversion to RGB, but an automatic process like `ufraw-batch` is by nature completely uncontrolled.

**Comment by linkyndy** [comment]
Thanks for the explanation. Unfortunately, the nature of our task demands we analyse all images that are uploaded.

I will temporarily disable RAW files then, until 8.8.1 is out. Do you have an estimate for this?

Also, is there something else we can do to RAW files so that we "tame" the resources a bit? Like scaling the image, or converting it to JPG or similar. Might that take a shorter amount of time/consume less resources?

**Comment by jcupitt** [comment]
8.8.1 should be in just a few days now.

I'm afraid that's just the nature of RAW processing: it does need a lot of CPU. Things like lightroom, for example, need a good GPU to work quickly.

I would display a generic "this is a RAW image" icon rather than a thumbnail, as most file managers and cloud storage providers do.

**Comment by linkyndy** [comment]
> 8.8.1 should be in just a few days now.

Awesome!

> I would display a generic "this is a RAW image" icon rather than a thumbnail, as most file managers and cloud storage providers do.

I might have described this the wrong way. We actually need to analyse the contents of the files. So, for that, we're loading the images and then writing them to memory as RGB arrays. I was wondering whether scaling/converting RAW images (instead of directly loading them) before writing them to memory might give better results.

**Comment by jcupitt** [comment]
Ah! Sorry, I forgot.

Yup, you have no choice then, you must pay the price of RAW support :-( 

You could potentially filter out those files and convert them on another server, I guess. Then only people who wanted to process these crazy things would see pain and delay, rather then every user being impacted.

**Comment by jcupitt** [comment]
Oh, I suppose one more thing you could do is to call `ufraw-batch` yourself.

Here's how imagemagick is doing the processing:

1. Copy file to `/tmp/xxxx.RAW`.
2. `system("ufraw-batch /tmp/xxxx.RAW /tmp/xxxx.pbm")`
3. Load the PBM into memory, unpacked to RGBAX, 16 bits per channel.
4. Hand the memory over to libvips a section at a time.
5. libvips repacks to RGB, 8 bits per channel.

Instead, you could do:

1. `system("ufraw-batch my-file-for-processing.RAW /tmp/xxxx.pbm")`
2. `Vips::Image.new_from_file("/tmp/xxxx.pbm")`

The libvips PBM loader is very fast -- it is able to mmap the file on demand and in parallel.

**Comment by jcupitt** [comment]
If you call ufraw yourself, you'll also be able to pass parameters to it, which might be useful for your users.

**Comment by linkyndy** [comment]
This sounds interesting. I might give it a try, if I'll have the time. Thank you! 🙌

**Comment by linkyndy** [comment]
Tried this with CR2/NEF images and got an improvement of 60-70%. Which is great, however I am curious how this would behave with really big RAW images (biggest one I tested with was 77MB).
