### ISSUE TITLE
Forget free context in vipsedit.c

### ISSUE THREAD

**Issue by zodf0055980** [libvips/libvips#1868]
I build it in ASan/MSan, and run vipsedit.
```
➜  libvips git:(master) ✗ ./tools/vipsedit 

usage: vipsedit [OPTION...] vips-file

=================================================================
==11521==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 88 byte(s) in 1 object(s) allocated from:
    #0 0x7f8e13ba1d28 in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xded28)
    #1 0x7f8e125aeb10 in g_malloc0 (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x51b10)

Indirect leak of 33 byte(s) in 1 object(s) allocated from:
    #0 0x7f8e13ba1b40 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb40)
    #1 0x7f8e125aeab8 in g_malloc (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x51ab8)

SUMMARY: AddressSanitizer: 121 byte(s) leaked in 2 allocation(s).
```

You forget to free context.
Maybe you should patch like this:
```
	if (argc != 2)
	{
		fprintf(stderr, _("usage: %s [OPTION...] vips-file\n"),
				g_get_prgname());
		g_option_context_free(context);
		g_option_group_unref(main_group);
		exit(0);
	}
	g_option_context_free(context);
        .....
        g_option_group_unref(main_group);
```
I think it also has to free `main_group` when unused it.

**Comment by jcupitt** [comment]
Ooop, more dumbness, thank you very much!

Fixed in git master.
