### ISSUE TITLE
Saving an svgload_buffer image throws a Cairo error

### ISSUE THREAD

**Issue by manthey** [libvips/libvips#2611]
## Bug report

**Describe the bug**
When trying to save a large svg image created with `svgload_buffer`, it fails with a cairo_t InvalidSize error.

**To Reproduce**
1. Using pyvips:
```
import pyvips
svgImage = pyvips.Image.svgload_buffer('<svg viewBox="0 0 57578 56112" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" fill="black" d="M 58815,54197 L 58252,54478 L 57689.,54760 L 58346,55510 L 58815,54197 z"/></svg>'.encode())
svgImage.tiffsave("sample.tiff", compression="lzw")
```
2. Use Configuration:
  Using a locally built version of vips (and almost all other packages, including librsvg 2.52.5.
```
vips --vips-config

enable debug: no
enable deprecated library components: yes
enable modules: yes
use fftw3 for FFT: no
accelerate loops with orc: yes
ICC profile support with lcms: no
zlib: yes
text rendering with pangocairo: yes
font file support with fontconfig: yes
RAD load/save: yes
Analyze7 load/save: yes
PPM load/save: yes
GIF load:  yes
EXIF metadata support with libexif: no
JPEG load/save with libjpeg: yes (pkg-config)
JXL load/save with libjxl: yes (dynamic module: yes)
JPEG2000 load/save with libopenjp2: yes
PNG load with libspng: no
PNG load/save with libpng: yes (pkg-config libpng >= 1.2.9)
quantisation to 8 bit: yes
TIFF load/save with libtiff: yes (pkg-config libtiff-4)
image pyramid save: yes
HEIC/AVIF load/save with libheif: yes (dynamic module: yes)
WebP load/save with libwebp: yes
PDF load with PDFium:  no
PDF load with poppler-glib: yes (dynamic module: yes)
SVG load with librsvg-2.0: yes
EXR load with OpenEXR: yes
OpenSlide load: yes (dynamic module: yes)
Matlab load with matio: no
NIfTI load/save with niftiio: yes
FITS load/save with cfitsio: yes
GIF save with cgif: no
Magick package: MagickCore (dynamic module: yes)
Magick API version: magick7
load with libMagickCore: yes
save with libMagickCore: yes
```
  Note, this works in vips-8.11.4 but not in vips-8.12.1

3. See error:
```
(process:2760): librsvg-WARNING **: 22:28:45.595: cannot render on a cairo_t with a failure status (status=InvalidSize)
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/usr/local/lib/python3.9/site-packages/pyvips/vimage.py", line 938, in call_function
    return pyvips.Operation.call(name, self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyvips/voperation.py", line 305, in call
    raise Error('unable to call {0}'.format(operation_name))
pyvips.error.Error: unable to call tiffsave
  svgload_buffer: SVG rendering failed
glib: rendering error: InvalidSize
```

**Expected behavior**
I expect to be able to save the generated image.

**Actual behavior**
An `InvalidSize` error is reported, and the image is not saved.

**Environment**
 - OS: testing on Ubuntu 20.04 and 18.04.
 - Vips: 8.12.1 (but 8.11.4 works)
 - Used pyvips 2.1.16 under python 3.9 (used in testing with both 8.12.1 and 8.11.4).

**Comment by jcupitt** [comment]
Hi @manthey,

> viewBox="0 0 57578 56112"

Unfortunately librsvg no longer supports SVGs larger than 32k x 32k pixels, so this no longer works.

We've been looking at other SVG rendering libraries, but no decision has been made yet on how to improve this.

https://github.com/libvips/libvips/discussions/2048

**Comment by manthey** [comment]
Thank you so much -- it is easy enough to tile things, so I'll go that route for my use case.  My use case is simple enough (just drawing polygons), that I could do it by means other than svg if I had to.  True svg support is hard...
