### ISSUE TITLE
libvips built without JPEG2000 support

### ISSUE THREAD

**Issue by skycovering** [libvips/libvips#2746]
Hello :)

I met an error when I use libvips to make Svs to Tiff: 
"pyvips.error.Error: unable to call VipsForeignSaveTiffFile
  jp2k: libvips built without JPEG2000 support"

This is my code:

```
import pyvips

img = pyvips.Image.new_from_file(r'D:\DN_data\pathml\wsi_data\20190294pas.svs',access='sequential')
img.write_to_file(r'D:\DN_data\pathml\wsi_data\test.tif')
```

And it's the result:

C:\Users\Skycovering-Big\.conda\envs\PY37\python.exe C:/Users/Skycovering-Big/PycharmProjects/pythonProject3/main.py
Traceback (most recent call last):
  File "C:/Users/Skycovering-Big/PycharmProjects/pythonProject3/main.py", line 4, in <module>
    img.write_to_file(r'D:\DN_data\pathml\wsi_data\elyjlejspas.tif')
  File "C:\Users\Skycovering-Big\.conda\envs\PY37\lib\site-packages\pyvips\vimage.py", line 547, in write_to_file
    string_options=options, **kwargs)
  File "C:\Users\Skycovering-Big\.conda\envs\PY37\lib\site-packages\pyvips\voperation.py", line 305, in call
    raise Error('unable to call {0}'.format(operation_name))
pyvips.error.Error: unable to call VipsForeignSaveTiffFile
  jp2k: libvips built without JPEG2000 support

**Comment by jcupitt** [comment]
Hi @skycovering, it sounds like you might have downloaded the `-web` build of libvips. This only includes common and well-tested file format support.

You need the `-all` build. This should have jp2k support:

https://github.com/libvips/build-win64-mxe/releases/tag/v8.12.2
