### ISSUE TITLE
OSError: [Errno 30] Read-only file system: '/my'

### ISSUE THREAD

**Issue by dythbj** [libvips/libvips#3973]
MacOS Sonoma 14.4.1, Apple M3 Pro

Building from source, like:
  meson setup build --prefix /my/install/prefix
  cd build
  meson compile
  meson test
  meson install

Every thing is Ok, before "meson install":

ninja: Entering directory `/Users/gaojie/Downloads/libvips-8.15.2/build'
ninja: no work to do.
Installing libvips/include/vips/enumtypes.h to /my/install/prefix/include/vips
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mesonbuild/mesonmain.py", line 186, in run
    return options.run_func(options)
  File "/usr/local/lib/python3.10/site-packages/mesonbuild/minstall.py", line 863, in run
    installer.do_install(datafilename)
  File "/usr/local/lib/python3.10/site-packages/mesonbuild/minstall.py", line 543, in do_install
    self.install_targets(d, dm, destdir, fullprefix)
  File "/usr/local/lib/python3.10/site-packages/mesonbuild/minstall.py", line 740, in install_targets
    file_copied = self.do_copyfile(fname, outname, makedirs=(dm, outdir))
  File "/usr/local/lib/python3.10/site-packages/mesonbuild/minstall.py", line 409, in do_copyfile
    dirmaker.makedirs(outdir, exist_ok=True)
  File "/usr/local/lib/python3.10/site-packages/mesonbuild/minstall.py", line 108, in makedirs
    self.makedirs_impl(path, exist_ok=exist_ok)
  File "/usr/local/lib/python3.10/site-packages/mesonbuild/minstall.py", line 309, in makedirs
    os.makedirs(*args, **kwargs)
  File "/usr/local/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 1 more time]
  File "/usr/local/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/my'

ERROR: Unhandled python OSError. This is probably not a Meson bug, but an issue with your build environment.

So, Any idea?

**Comment by jcupitt** [comment]
Hello @dythbj,

> meson setup build --prefix /my/install/prefix

You need to pick an install prefix. I often use `/Users/john/vips`, for example.

It's probably simpler to use homebrew though. Just `brew install vips` and it should do everything for you.
