### ISSUE TITLE
Problem with vips module loading in Azure Windows host

### ISSUE THREAD

**Issue by kristian-kablas** [libvips/libvips#4148]
Hi,
we are using NetVips bindings to convert PDF file into images in Asp.net web application. On local Windows 10 machines everything works. We deployed app to test env in Azure and app fails to convert file. After enabling logs, we can see that vips is failing to load module dlls.

Windows dlls (v8.15.3) are downloaded from https://github.com/libvips/build-win64-mxe/releases.

Application is deployed to Azure Functions running on Windows host. We also tried to deploy app to Azure App Services (Windows host) and the result is same.

I am not sure if the problem is that module paths contain forward slash but i don't see what else could be wrong. I don't know what else we can try so I'm asking for you help.
Thank you!
<br/>

Logs from Azure Functions:

Vips logs
```
VIPS-INFO: 11:45:07.215: VIPS_PREFIX = /data/mxe/usr/x86_64-w64-mingw32.shared.all
VIPS-INFO: 11:45:07.230: VIPS_LIBDIR = /data/mxe/usr/x86_64-w64-mingw32.shared.all/lib
VIPS-INFO: 11:45:07.230: prefix = C:\home\site\wwwroot
VIPS-INFO: 11:45:07.230: libdir = C:\home\site\wwwroot
VIPS-INFO: 11:45:07.558: searching "C:\home\site\wwwroot/vips-modules-8.15"
VIPS-INFO: 11:45:07.590: loading "C:\home\site\wwwroot/vips-modules-8.15\vips-jxl.dll"
VIPS-WARNING **: 11:45:07.605: unable to load "C:\home\site\wwwroot/vips-modules-8.15\vips-jxl.dll" -- 'C:\home\site\wwwroot/vips-modules-8.15\vips-jxl.dll': The specified module could not be found.
VIPS-INFO: 11:45:07.605: loading "C:\home\site\wwwroot/vips-modules-8.15\vips-magick.dll"
VIPS-WARNING **: 11:45:07.621: unable to load "C:\home\site\wwwroot/vips-modules-8.15\vips-magick.dll" -- 'C:\home\site\wwwroot/vips-modules-8.15\vips-magick.dll': The specified module could not be found.
VIPS-INFO: 11:45:07.621: loading "C:\home\site\wwwroot/vips-modules-8.15\vips-openslide.dll"
VIPS-WARNING **: 11:45:07.652: unable to load "C:\home\site\wwwroot/vips-modules-8.15\vips-openslide.dll" -- 'C:\home\site\wwwroot/vips-modules-8.15\vips-openslide.dll': The specified module could not be found.
VIPS-INFO: 11:45:07.652: loading "C:\home\site\wwwroot/vips-modules-8.15\vips-poppler.dll"
VIPS-WARNING **: 11:45:07.668: unable to load "C:\home\site\wwwroot/vips-modules-8.15\vips-poppler.dll" -- 'C:\home\site\wwwroot/vips-modules-8.15\vips-poppler.dll': The specified module could not be found.
```

NetVips stacktrace:
```
NetVips.VipsException: no such operation pdfload_buffer
VipsOperation: class "pdfload_buffer" not found
   at NetVips.Operation.NewFromName(String operationName)
   at NetVips.Introspect..ctor(String operationName)
   at NetVips.Introspect.<>c.<Get>b__10_0(String name)
   at NetVips.Introspect.<>c.<Get>b__10_0(String name)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at NetVips.Introspect.Get(String operationName)
   at NetVips.Operation.Call(String operationName, VOption kwargs, Image matchImage, Object[] args)
   at NetVips.Operation.Call(String operationName, VOption kwargs, Object[] args)
   at NetVips.Image.PdfloadBuffer(Byte[] buffer, Nullable`1 page, Nullable`1 n, Nullable`1 dpi, Nullable`1 scale, Double[] background, String password, Nullable`1 memory, Nullable`1 access, Nullable`1 failOn)
```

System info:
Azure Functions
OS version: Microsoft Windows NT 10.0.14393.0
64 bit: True
Processor count: 2
CLR version: 4.0.30319.42000

Vips module dlls are present in Azure:
![image](https://github.com/user-attachments/assets/b54ebe84-ccb5-4873-a540-3a4dd63fcfd0)

**Comment by kleisauke** [comment]
Did you remove the [`NetVips.Native`](https://www.nuget.org/packages/NetVips.Native) package? This NuGet package is unnecessary if you have libvips installed globally, which is also why it can be optionally installed. Keeping it may cause conflicts.

**Comment by kristian-kablas** [comment]
> Did you remove the [`NetVips.Native`](https://www.nuget.org/packages/NetVips.Native) package? This NuGet package is unnecessary if you have libvips installed globally, which is also why it can be optionally installed. Keeping it may cause conflicts.

Hello, we are not using `NetVips.Native` package because it does not contain dll that is needed to use "pdfload_buffer" method.

**Comment by kleisauke** [comment]
I assume the other DLLs like `libvips-42.dll` are located in `C:\home\site\wwwroot` and this directory is on the `PATH` environment variable? Also, does `vips copy x.pdf x.png` work?

**Comment by MetaTwice** [comment]
I suspect it's probably because you are using the `bin` folder from the web version `vips-dev-w64-web` try the `bin` from all `vips-dev-w64-all` . 

You can also use this to test https://github.com/kleisauke/net-vips/issues/62#issuecomment-585203348

**Comment by kleisauke** [comment]
@kristian-kablas Were you able to make any progress with this? It may also be necessary to adjust your 64-bit or 32-bit setting, depending on the libvips you are using, see: https://github.com/libvips/libvips/issues/1608#issuecomment-615256089.

**Comment by Prateek-coder19** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by kleisauke** [comment]
Closing due to inactivity. Please feel free to re-open if there's still a problem.
