### ISSUE TITLE
Unreachable error when calling vips_init() in Cloudflare Workers environment (WASM)

### ISSUE THREAD

**Issue by mojodevagentsix** [libvips/libvips#4215]
I'm encountering an issue when trying to use libvips compiled to WebAssembly within a Cloudflare Workers environment. Specifically, the vips_init() function is throwing an "unreachable" error.

Environment:

Cloudflare Workers
libvips compiled to WebAssembly using Emscripten

Steps to Reproduce:

1. Compile libvips to WebAssembly using Emscripten with the flags listed below.
2. Load the resulting .wasm file in a Cloudflare Worker.
3. Attempt to call the vips_init() function.

Expected Behavior: The vips_init() function should initialize libvips successfully.

Actual Behavior: An "unreachable" error is thrown when calling vips_init().

Error Message:

`Error in vips_init: RuntimeError: unreachable
    at vips-es6.wasm.vips_init (vips-es6.wasm-01392cc6:0x12c496)
    at Object.fetch (index.js:165:47)
    at async jsonError (.internal-6d243f3f-ce0c-4f2f-bbd2-40a2a2c4db25-facade-1.js:12:12)`

Compilation Flags:

`-sAUTOLOAD_DYLIBS=0
-sABORTING_MALLOC=0
-sSTANDALONE_WASM
-sERROR_ON_UNDEFINED_SYMBOLS=0
-sMODULARIZE
-sEXPORT_NAME='Vips'
-sINITIAL_MEMORY=134217728
-sMAXIMUM_MEMORY=134217728
-sSTACK_SIZE=8MB
-gsource-map
-sALLOW_TABLE_GROWTH
-sALLOW_MEMORY_GROWTH=0
-sTEXTDECODER=2
-sASSERTIONS=2
-sFORCE_FILESYSTEM=0
-sMALLOC='emmalloc'
-sUSE_OFFSET_CONVERTER
-sVERBOSE=1
-sDEMANGLE_SUPPORT=1
-sEXPORTED_FUNCTIONS=_get_vips_version
--no-entry
-sEXCEPTION_STACK_TRACES
-sBINARYEN_EXTRA_PASSES=--emit-target-features
--profiling
--profiling-funcs
--keep-names
--emit-symbol-map
--threadprofiler
-sSAFE_HEAP=1
-sCHECK_NULL_WRITES=0
-sLIBRARY_DEBUG
-sEXCEPTION_DEBUG
-sSYSCALL_DEBUG
-sDYLINK_DEBUG
-sSTACK_OVERFLOW_CHECK=2
-sRUNTIME_DEBUG=1
-Os  # Optimize for size
-g  # Include debug information`

Additional Context:

- The same WebAssembly module works correctly when used in a browser environment with index.html or React.
- The native C version of the code works as expected.
- The issue only occurs in the Cloudflare Workers environment.

Questions

1. Are there known issues with running libvips in a Cloudflare Workers environment?
2. Are there specific memory or environment settings required for libvips to initialize properly in this context?
3.  Could this be related to the memory limitations or execution environment of Cloudflare Workers?
4. Are there any flags in our compilation settings that might be causing conflicts in the Workers environment?
5. Is the fixed memory allocation (-sALLOW_MEMORY_GROWTH=0) a potential issue in the Workers context?

Observations:

1. We're using a fixed memory allocation (134217728 bytes, or 128MB) without growth.
2. The stack size is set to 8MB(tested with 256kb, 2MB, 4MB but same error), which might be larger than necessary for a Worker environment.
3. We're using emmalloc as the memory allocator, which is optimized for size but might have different behavior than the default allocator.
4. Many debug flags are enabled, which could impact performance but should help with diagnosing the issue.

Any insights or suggestions on how to resolve this "unreachable" error when initializing libvips in a Cloudflare Workers environment, particularly considering our compilation settings, would be greatly appreciated.

**Comment by kleisauke** [comment]
Please see https://github.com/kleisauke/wasm-vips/issues/2.
